---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "X_NAME_PLACEHOLDER_X"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "X-ROLE-PLACEHOLDER-X"
subjects:
- kind: "ServiceAccount"
  name: "X-SERVICEACCOUNT-PLACEHOLDER-X"
  namespace: "X-NAMESPACE-PLACEHOLDER-X"
...
